project:
  type: website
  output-dir: docs
  
#adds different tabs with .qmds to my site
website:
  title: "Olivia Ceminsky"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - mini_project1_ceminsky.qmd
      - miniproject2.qmd
      - mini_project4.qmd
      - research.qmd
    right: 
      - icon: github
        href: https://github.com/oceminsky/oceminsky.github.io

#creates a theme and colors for the site
format:
  html:
    theme: 
      light: yeti
      dark: superhero
    css: styles.css
    toc: true
    page-layout: full

editor: visual

