project:
  type: website
  output-dir: docs

website:
  title: "Olivia Ceminsky"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - mini_project1_ceminsky.qmd
      - miniproject2.qmd
      - research.qmd

format:
  html:
    theme: 
      light: yeti
      dark: superhero
    css: styles.css
    toc: true
    page-layout: full

editor: visual

